### ISSUE TITLE
Vagrant up has errors

### ISSUE THREAD

**Issue by stegmannc** [dwalldorf/owTracker#25]
==> default: Error: Could not set 'link' on ensure: No such file or directory - /usr/share/nginx/owt/web/lib at 13:/tmp/vagrant-puppet/modules-10603e210189d6068ba3c680b1c862bd/owt/manifests/config.pp
==> default: Error: Could not set 'link' on ensure: No such file or directory - /usr/share/nginx/owt/web/lib at 13:/tmp/vagrant-puppet/modules-10603e210189d6068ba3c680b1c862bd/owt/manifests/config.pp
==> default: Wrapped exception:
==> default: No such file or directory - /usr/share/nginx/owt/web/lib
==> default: Error: /Stage[main]/Owt::Config/File[node_modules_symlink]/ensure: change from absent to link failed: Could not set 'link' on ensure: No such file or directory - /usr/share/nginx/owt/web/lib at 13:/tmp/vagrant-puppet/modules-10603e210189d6068ba3c680b1c862bd/owt/manifests/config.pp

The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by dwalldorf** [comment]
caused by #26
