### ISSUE TITLE
missing php5 mongo extension

### ISSUE THREAD

**Issue by stegmannc** [dwalldorf/owTracker#26]
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/mongodb 1.2.2 -> satisfiable by doctrine/mongodb[1.2.2].
    - doctrine/mongodb 1.2.2 requires ext-mongo ^1.2.12 -> the requested PHP extension mongo is missing from your system.
  Problem 2
    - doctrine/mongodb 1.2.2 requires ext-mongo ^1.2.12 -> the requested PHP extension mongo is missing from your system.
    - doctrine/mongodb-odm 1.0.5 requires doctrine/mongodb ~1.2 -> satisfiable by doctrine/mongodb[1.2.2].
    - Installation request for doctrine/mongodb-odm 1.0.5 -> satisfiable by doctrine/mongodb-odm[1.0.5].

  To enable extensions, verify that they are enabled in those .ini files:
    - /etc/php5/cli/php.ini
    - /etc/php5/cli/conf.d/05-opcache.ini
    - /etc/php5/cli/conf.d/10-pdo.ini
    - /etc/php5/cli/conf.d/20-intl.ini
    - /etc/php5/cli/conf.d/20-json.ini
    - /etc/php5/cli/conf.d/20-memcached.ini
    - /etc/php5/cli/conf.d/20-readline.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
PHP Warning:  require(/usr/share/nginx/owt/app/../vendor/autoload.php): failed to open stream: No such file or directory in /usr/share/nginx/owt/app/autoload.php on line 9
PHP Fatal error:  require(): Failed opening required '/usr/share/nginx/owt/app/../vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /usr/share/nginx/owt/app/autoload.php on line 9

**Comment by dwalldorf** [comment]
resolved by 0f9752514ffe04739732da629ad83c6e215fde69
